const CONFIG = {
  webhookUrl: 'https://n8n.srv1326537.hstgr.cloud/webhook-test/maintenance-submit',

  properties: [
    'Sunrise Apartments - Unit 101',
    'Sunrise Apartments - Unit 102',
    'Sunrise Apartments - Unit 103',
    'Sunrise Apartments - Unit 201',
    'Sunrise Apartments - Unit 202',
    'Sunrise Apartments - Unit 203',
    'Maple Street House - 14 Maple St',
    'Maple Street House - 16 Maple St',
    'Cedar Ridge Duplex - 42A Cedar Ridge',
    'Cedar Ridge Duplex - 42B Cedar Ridge',
  ],

  problemTypes: [
    'Plumbing – Leak or drip',
    'Plumbing – Clogged drain',
    'Plumbing – No hot water',
    'Plumbing – Running toilet',
    'Plumbing – Low water pressure',
    'Electrical – Outlet not working',
    'Electrical – Light fixture',
    'Electrical – Breaker tripping',
    'HVAC – No heat',
    'HVAC – No cooling / AC',
    'HVAC – Strange noise',
    'Appliance – Refrigerator',
    'Appliance – Stove / Oven',
    'Appliance – Dishwasher',
    'Appliance – Washer / Dryer',
    'Doors & Locks – Lock not working',
    'Doors & Locks – Door not closing',
    'Windows – Broken glass',
    'Windows – Won\'t open or close',
    'Pest – Insects',
    'Pest – Rodents',
    'Structural – Wall damage',
    'Structural – Ceiling damage',
    'Structural – Flooring',
    'Exterior – Parking / Driveway',
    'Other',
  ],

  locations: [
    'Entire unit',
    'Kitchen',
    'Bathroom – Main',
    'Bathroom – Secondary',
    'Living room',
    'Master bedroom',
    'Bedroom 2',
    'Bedroom 3',
    'Hallway / Entryway',
    'Laundry room',
    'Garage',
    'Basement',
    'Attic',
    'Exterior / Outside',
    'Balcony / Patio',
  ],
};
